# Generated by Django 2.2.7 on 2022-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, verbose_name='Заголовок объявления')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата объявления')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка на объявление')),
            ],
        ),
    ]
