# Generated by Django 2.2.7 on 2022-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='val',
            field=models.TextField(blank=True, default='BYN', verbose_name='Валюта'),
        ),
    ]
