# Generated by Django 2.2.7 on 2022-08-22 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20220822_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата объявления'),
        ),
        migrations.AlterField(
            model_name='appartament',
            name='url',
            field=models.URLField(max_length=100, unique=True, verbose_name='Ссылка на объявление'),
        ),
    ]
