# Generated by Django 2.2.7 on 2022-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20220822_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='url',
            field=models.URLField(max_length=100, verbose_name='Ссылка на объявление'),
        ),
    ]
