# Generated by Django 2.2.7 on 2022-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20220822_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата объявления'),
        ),
    ]
