# Generated by Django 2.2.7 on 2022-08-22 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20220822_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartament',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата объявления'),
        ),
    ]
